#!/bin/sh

set -e

#_MIRROR="http://ftp.fr.debian.org/debian/"
_MIRROR="http://localhost:3142/debian/"

lb config noauto \
	 --clean \
   --ignore-system-defaults \
   --distribution sid \
   --mode debian \
   --debian-installer live \
   --debian-installer-distribution daily \
   --linux-packages "linux-image linux-headers" \
   --firmware-binary false \
   --firmware-chroot false \
   --source false \
   --mirror-bootstrap "${_MIRROR}" \
   --parent-mirror-bootstrap "${_MIRROR}" \
   --parent-mirror-chroot "http://httpredir.debian.org/debian" \
   --parent-mirror-binary "http://httpredir.debian.org/debian" \
   --archive-areas "main contrib non-free" \
   --binary-images iso \
   --bootloaders grub-efi \
   --loadlin false \
   --win32-loader false \
   --uefi-secure-boot disable \
"${@}"

