#!/bin/sh

set -e

_MIRROR="http://debian.proxad.net/debian/"

lb config noauto \
	 --clean \
   --distribution buster \
   --ignore-system-defaults \
   --mode debian \
   --debian-installer live \
   --linux-packages "linux-image linux-headers" \
   --source false \
   --parent-mirror-bootstrap "${_MIRROR}" \
   --archive-areas "main contrib non-free" \
   --firmware-binary true \
   --firmware-chroot true \
   --binary-images hdd \
   --binary-filesystem ext4 \
   --chroot-filesystem ext4 \
   --bootloaders grub-efi \
"${@}"
