#!/bin/sh

set -e

_MIRROR="http://httpredir.debian.org/debian"
_PROXY="http://localhost:3142/"
git clean -fX
lb config noauto \
	 --clean \
   --ignore-system-defaults \
   --distribution sid \
   --mode debian \
   --debian-installer live \
   --debian-installer-distribution unstable \
   --linux-packages "linux-image linux-headers" \
   --firmware-binary false \
   --firmware-chroot false \
   --source false \
   --mirror-bootstrap "${_MIRROR}" \
   --mirror-binary "${_MIRROR}" \
   --mirror-debian-installer "${_MIRROR}" \
   --apt-http-proxy "${_PROXY}" \
   --archive-areas "main contrib non-free" \
   --binary-images iso \
   --bootloaders grub-efi \
   --bootappend-live "boot=live components config keyboard-layouts=fr" \
   --bootappend-install "keyboard-layouts=fr" \
   --loadlin false \
   --win32-loader false \
   --uefi-secure-boot disable \
"${@}"

